### ISSUE TITLE
Concatenate Title Field.

### ISSUE THREAD

**Issue by cj** [datocms/feature-requests#100]
Rather than only being able to choose one field for your title field, it would be great to be able to concatenate multiple fields.

![](https://cl.ly/c6fd46836917/Image%2525202018-10-20%252520at%2525203.56.17%252520PM.png)

For example a School has classes, with a `Name` field that has `English,Maths` etc.., but it also has a `Grade` field `K-1, 1-5, 5-8, 6-8, 9-Young Adult, Homeschool`.  So in this instance you'll want the `Title field` to be `Name + Grade`, because if you just have `Name` or `Grade` you will not actually know which one you are selecting i.e. `Math, K-1` or `Math, 1-5`, as all that will show up for the referenced model is `Math` and `Math`.

**Comment by stefanoverna** [comment]
This plugin by the awesome @cj solves the problem! https://www.datocms.com/plugins/i/datocms-plugin-better-links/
