### ISSUE TITLE
Collapse moduler content panels

### ISSUE THREAD

**Issue by ec8or** [datocms/feature-requests#104]
It would be nice if it were possible to collapse modular content blocks as it can get a bit unwieldy and hard to find what you're looking for when you have a lot of them saved on something like a page.

Something like this:

![image](https://user-images.githubusercontent.com/1678184/47434586-be279280-d79a-11e8-8e68-d4ecc35bbde7.png)

You can already achieve this using the Conditional Plugin but it's a pain to have to define and add every field, and a more standard toggle would make more sense if you're showing/hiding all fields.

**Comment by stefanoverna** [comment]
Its in the works!

**Comment by stefanoverna** [comment]
Online now!
