### ISSUE TITLE
Configurable Twitter Cards

### ISSUE THREAD

**Issue by tonycamaiani** [datocms/feature-requests#105]
Right now  all Twitter Cards are all set up as *Summary* 
<meta name=“twitter:card” content=“summary”>

but I would like to change them to be *Summary with Large image* 
<meta name=“twitter:card” content=“summary_large_image”>

To make this more generic, maybe add in the SEO setting a dropdown where you can pick what kind of Twitter Cards you want to use

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html

**Comment by stefanoverna** [comment]
Done! https://www.datocms.com/changelog/configurable-twitter-card/
