### ISSUE TITLE
Plugins uninstall notification not working properly

### ISSUE THREAD

**Issue by NegativeKarma** [datocms/feature-requests#110]
When unistalling a plugin the notification "Couldn't delete plugin" pops up, but the disinstallation worked.

The notification might be popping up because on the right side the "content" of the plugin is still visible.
![screenshot 2018-11-09 at 12 56 30](https://user-images.githubusercontent.com/11423239/48261330-fd064b00-e41e-11e8-84f0-bd9554f2f9a0.png)

Also refreshing the plugin section of the dashboard crashes the project and instead moving to a different section of the dashboard works fine.

**Comment by stefanoverna** [comment]
Fixed, thanks!
