### ISSUE TITLE
Optional translations

### ISSUE THREAD

**Issue by stefanoverna** [datocms/feature-requests#29]
It would be great if you could configure a certain model so that you are not forced to insert content for EVERY language your administrative area supports, but manually add the locales you want, depending on the specific record.

**Comment by lapidus** [comment]
+1

**Comment by Convincible** [comment]
Yes, although this is easy enough to workaround – just don't enter anything in the other languages!

**Comment by stefanoverna** [comment]
It's live! https://www.datocms.com/changelog/optional-translations-now-available/

**Comment by stefanoverna** [comment]
Records only contain the filled in locales, there will be no locale key for the ones non-specified.
