### ISSUE TITLE
Dependencies between fields

### ISSUE THREAD

**Issue by stefanoverna** [datocms/feature-requests#30]
It would be great if you could: 
   
 * show a field A only if field B is checked/has some value  
 * force a "required" validation on field A only if field B is checked/has some value

**Comment by Convincible** [comment]
* Tie default values from any field to any other field (not just for slugs)

**Comment by stefanoverna** [comment]
Implemented as a DatoCMS plugin! https://github.com/datocms/plugins/tree/master/conditional-fields/
