### ISSUE TITLE
Customise options in HTML/Markdown Editor

### ISSUE THREAD

**Issue by stefanoverna** [datocms/feature-requests#6]
Would be great to be able to customise the editor toolbar and remove certain things.   I'd like to allow only certain types of styling (e.g. only <i>italic</i>, no <b>bold</b>) or prevent clients from adding images. 
 

-----

Originally posted by admin@philipppolder.com

**Comment by stefanoverna** [comment]
Yes please! 
 

-----

Originally posted by webmaster@convincible.media

**Comment by Convincible** [comment]
One of the great things about the DatoCMS approach is we can protect clients from their own WYSIWYG nightmares. However, many clients find Markdown scary. I want to give them the HTML field, but:
1. Disable things they aren't meant to add in that field, e.g. headings, tables, links
2. Aggressively sanitise what they paste into this box. It should automatically:
   * Pare things right back to basic HTML (`p`, `em`, etc) with minimal nesting
   * Remove any inline styling e.g. `<span style="...">`
   * Fix any other glitches you get when pasting from MS Word e.g. random `&nbsp;`, `mso` classes, etc.

**Comment by stefanoverna** [comment]
Now you can customize buttons!
