### ISSUE TITLE
Add ability to have all save events trigger build process

### ISSUE THREAD

**Issue by chenware** [datocms/feature-requests#69]
As a CMS user, I want all save events to be reflected on the website without needing to trigger a build as a separate action.

**Comment by stefanoverna** [comment]
Hi Robb, you can have this using Webhooks (
https://www.datocms.com/docs/introduction/webhooks/). Just connect a
Netlify build hook
(https://www.netlify.com/docs/webhooks/#incoming-webhooks) to
a DatoCMS webook that triggers on all the records events
(create/update/delete/publish/unpublish).

2018-08-04 19:05 GMT+02:00 Robb Chen-Ware <notifications@github.com>:

**Comment by chenware** [comment]
Ah, point of confusion with customer service then –  got it set up and working in no time. Thanks!
