### ISSUE TITLE
Integration with Shopify

### ISSUE THREAD

**Issue by macs91** [datocms/feature-requests#85]
Enable the content editor to pick products from Shopify (e.g. featured products in home page).

This of course would be good for any other platform, like Magento.. Therefore the most flexible implementation would be to enable custom integrations with dato. 

A possible implementation of this could be to enable the creation of custom presentation UI for the JSON field. For example, the Shopify product picker could be implemented as a UI that stores the selected product data to JSON under the hood.

**Comment by stefanoverna** [comment]
UI Extensions are almost ready! :)

**Comment by lapidus** [comment]
@macs91: I have the exact same need in one project. Maybe we can collaborate on a product picker in a shared repo somewhere?  :)

**Comment by macs91** [comment]
@lapidus Yeah sure, once they'll release UI extensions we can work on it

**Comment by stefanoverna** [comment]
Alright folks, plugins are online! https://www.datocms.com/docs/plugins/introduction/

**Comment by stefanoverna** [comment]
Here's some examples: https://github.com/datocms/plugins

**Comment by stefanoverna** [comment]
Update: we're working on a shopify plugin ourselves.. stay tuned :)

**Comment by macs91** [comment]
@stefanoverna well that's awesome! 🚀

**Comment by stefanoverna** [comment]
Alright, it's here! https://github.com/datocms/plugins/tree/master/shopify-product/

**Comment by macs91** [comment]
I suggest that another that would be really useful is the shopify-collection one.. Mostly when working with Shopify you deal with produt collections
