### ISSUE TITLE
Visualization of linked records in linked model

### ISSUE THREAD

**Issue by souljuse** [datocms/feature-requests#92]
Reverse link for a relationship/link field, e.g. if I choose a particular item from one side of the relationship, it'd be nice if there was a field that appeared (whether editable or not) on the linked item's edit screen to show (or edit) the related items

**Comment by stefanoverna** [comment]
Somewhat related to #98

**Comment by stefanoverna** [comment]
Done! https://www.datocms.com/plugins/i/datocms-plugin-inverse-relationships/
